vich_uploader:
    db_driver: orm
<<<<<<< HEAD

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
=======
    metadata:
        type: attribute

    mappings:
        circuit_images:
           uri_prefix: /image/uploads/circuits
           upload_destination: '%kernel.project_dir%/public/image/uploads/circuits'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
        discover_images:
            uri_prefix: /image/uploads/discovers
            upload_destination: '%kernel.project_dir%/public/image/uploads/discovers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        producer_images:
            uri_prefix: /image/uploads/producers
            upload_destination: '%kernel.project_dir%/public/image/uploads/producers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
>>>>>>> 15f43c367831ffc1b62fdafb4c885cdda2422bf2
